In [1]:
import pandas as pd
import numpy as np

In [2]:
dict = {
    "name":["vihan","singh"],
    "age":[19,20],
    "L":["K","H"]
}
df1 = pd.DataFrame(dict)

In [3]:
df1

    name  age  L
0  vihan   19  K
1  singh   20  H

In [4]:
df1.to_csv('temp.csv', index = False)

In [5]:
dict = {
     "random number": (np.random.random(5) * 10).astype('int64'),
     "index": np.arange(5)
 }
new = pd.DataFrame(dict)
new.set_index("index", drop=True,inplace=True)
new

       random number
index
0                  2
1                  5
2                  7
3                  5
4                  9

In [7]:
new = pd.DataFrame((np.random.random((100,2)) * 100).astype(np.int64), columns=["first","second"])
new.head(3)

   first  second
0      9      66
1     13      29
2     97      65

In [11]:
new.describe() #this itself is a data frame

            first      second
count  100.000000  100.000000
mean    50.350000   48.660000
std     29.169437   27.888023
min      5.000000    0.000000
25%     21.000000   27.000000
50%     50.000000   46.500000
75%     76.000000   73.000000
max     99.000000   99.000000

In [14]:
arr = new.to_numpy()
arr = arr.flatten()
arr[10:20]

array([36,  8, 40, 32, 19, 26, 18, 28, 71, 52])

In [15]:
new.loc[0,"first"] = 15
new.head()
new = new.sort_values('first')
print(new.head())
new.reset_index(drop = True,inplace=True)
new.head()

    first  second
38      5      15
56      7      60
72      7      97
71      8      79
14      9      81

   first  second
0      5      15
1      7      60
2      7      97
3      8      79
4      9      81

In [10]:
arr = np.arange(20)
arr.shape = (5,4)

In [11]:
df1 = pd.DataFrame(arr, columns=["A","B","C","D"])

In [12]:
df1

    A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [13]:
data = {
    "Name": ["A","B","C"],
    "Age": [20,25,30],
    "Salary": [30000,40000,50000]
}

df = pd.DataFrame(data)
print(df)

  Name  Age  Salary
0    A   20   30000
1    B   25   40000
2    C   30   50000

In [16]:
df.loc[df["Age"] >= 25,["Age","Salary"]] = [45,600000]

In [17]:
df

  Name  Age  Salary
0    A   20   30000
1    B   45  600000
2    C   45  600000

In [21]:
df.isna().any()

Name      False
Age       False
Salary    False
dtype: bool

In [22]:
df[df["Name"].isin(["A","C"])]

  Name  Age  Salary
0    A   20   30000
2    C   45  600000

In [17]:
df = pd.read_csv(r"C:\Users\vihan\Downloads\pandas_demo_dataset.csv")

In [18]:
df.head()

   EmployeeID   Name Department     City   Age    Salary  Experience  Rating
0        1075   Neha         HR    Delhi  46.0   80658.0           1     2.1
1        1142  Arjun      Sales  Chennai  59.0  112886.0          14     3.4
2        1173  Karan         IT   Mumbai  50.0  112958.0          16     4.8
3        1039   Riya         IT  Chennai  48.0   76745.0           7     3.9
4        1052   Amit  Marketing   Mumbai  39.0   29432.0           7     3.3

In [19]:
df.groupby("City").agg({"Salary":["mean","sum"],
                       "Name":"count"})

                 Salary             Name
                   mean        sum count
City
Bangalore  66236.642857  1854626.0    29
Chennai    66892.944444  2408146.0    37
Delhi      73561.314286  2574646.0    38
Kolkata    68417.209302  2941940.0    47
Mumbai     68774.105263  2613416.0    39

In [20]:
df.groupby("Department")["Name"].count()

Department
Finance      39
HR           35
IT           43
Marketing    44
Sales        29
Name: Name, dtype: int64

In [21]:
df[df["Age"] > 50].tail()

,EmployeeID,Name,Department,City,Age,Salary,Experience,Rating
182,1154,Neha,Marketing,Bangalore,57.0,67101.0,6,3.6
183,1049,Arjun,IT,Delhi,57.0,NaN,1,1.8
186,1170,Riya,Finance,Kolkata,53.0,84383.0,16,NaN
187,1125,Amit,IT,Delhi,57.0,52139.0,7,3.4
188,1121,Pooja,IT,Delhi,58.0,117436.0,15,3.9

In [23]:
df["Age"].isna().any()

np.False_

In [24]:
df.loc[:, "Age"] = df["Age"].fillna(df["Age"].mean())
df.loc[:, "Salary"] = df["Salary"].fillna(df["Salary"].median())

In [25]:
df.loc[df["Salary"] < 30000,"Salary"] = 40000

In [45]:
df[df.duplicated()]

,EmployeeID,Name,Department,City,Age,Salary,Experience,Rating,New
63,1095,Arjun,HR,Delhi,22.0,98794.0,18,1.5,2173468.0
70,1110,Rahul,Sales,Kolkata,53.0,109659.0,11,3.4,5811927.0
104,1041,Vikas,HR,Delhi,53.0,106818.0,18,4.3,5661354.0
116,1081,Arjun,Marketing,Bangalore,47.0,71271.0,12,4.9,3349737.0
134,1097,Vikas,IT,Kolkata,50.0,51734.0,3,4.5,2586700.0
144,1141,Pooja,Finance,Chennai,28.0,53746.0,7,2.1,1504888.0
161,1137,Vikas,HR,Kolkata,52.0,63110.0,13,2.0,3281720.0
167,1176,Amit,Marketing,Mumbai,49.0,64809.0,16,4.4,3175641.0
177,1061,Sneha,Marketing,Delhi,43.0,40000.0,7,3.5,1077365.0
178,1050,Neha,HR,Kolkata,56.0,44262.0,13,1.1,2478672.0

In [52]:
dict1 = {
    "id" : np.array(["ABC" + str(x) for x in (np.random.rand(10) * 100).astype('int64')]),
    "age" : (np.random.rand(10) * 100).astype('int64')
}

df = pd.DataFrame(dict1)
df.head()

      id  age
0  ABC75   20
1  ABC45   35
2  ABC61   86
3  ABC15   39
4  ABC43   35

In [53]:
df.sort_values('id', inplace = True)
df.set_index('id',drop=True,inplace=True)

In [30]:
df.head()

       age
id
ABC15   28
ABC33   37
ABC64   77
ABC65   48
ABC65   88

In [32]:
df.index = df.index.str.replace('ABC', 'A@panda')
df.head()

           age
id
A@panda15   28
A@panda33   37
A@panda64   77
A@panda65   48
A@panda65   88

In [37]:
df.rename(columns={'age': 'Age'}, inplace=True)
df.rename(index={"A@panda15": 'A@panda15k'}, inplace=True)

In [38]:
df.head()

            Age
id
A@panda15k   28
A@panda33    37
A@panda64    77
A@panda65    48
A@panda65    88

In [39]:
bios = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv")

In [40]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [41]:
india_bios = bios[ ( bios["born_country"] == "IND" ) & ( bios["NOC"] == "India" )]
india_bios.reset_index(drop = True,inplace = True)
india_bios.head(10)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01
1,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN
2,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN
3,276,Vijay Amritraj,1953-12-14,Chennai (Madras),Tamil Nadu,IND,India,193.0,75.0,NaN
4,279,Mahesh Bhupathi,1974-06-07,Chennai (Madras),Tamil Nadu,IND,India,185.0,88.0,NaN
5,280,Ali Athar Fyzee,1883-08-28,Mumbai,Maharashtra,IND,India,NaN,NaN,1963-11-03
6,282,S. M. Hadi,1899-08-12,Hyderabad,Andhra Pradesh,IND,India,NaN,NaN,1971-07-14
7,283,Sydney Jacob,1879-10-28,Kasauli,Himachal Pradesh,IND,India,NaN,NaN,1977-02-14
8,284,Ramesh Krishnan,1961-06-05,Chennai (Madras),Tamil Nadu,IND,India,170.0,63.0,NaN
9,286,Kamlesh Mehta,1960-05-01,Mumbai,Maharashtra,IND,India,NaN,NaN,NaN

In [51]:
bios.loc[:,"born_country"].value_counts()

born_country
USA       9641
GER       6891
GBR       5792
FRA       5143
ITA       4709
          ...
SEY          1
SMT          1
COK          1
Corfu        1
Aarhus       1
Name: count, Length: 236, dtype: int64